---
plugins:
  - "rubocop-rake"
  - "rubocop-rspec"
AllCops:
  NewCops: "enable"
  TargetRubyVersion: "2.5"
Layout/HashAlignment:
  EnforcedHashRocketStyle: "table"
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: "comma"
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: "comma"
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: "comma"
